services:

  whoami:
    image: traefik/whoami:latest
    container_name: openresty-whoami
    restart: "no"
    stdin_open: false
    tty: true
    hostname: openresty-whoami
    networks:
      - default
    labels:
      traefik.enable: false

  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/mmguero/openresty-cyoa:latest
    container_name: openresty
    hostname: openresty
    restart: "no"
    stdin_open: false
    tty: true
    env_file:
      - .env
    depends_on:
      - whoami
    ports:
      - "127.0.0.1:443:443"
    networks:
      - default
    volumes:
    - type: bind
      bind:
        create_host_path: false
      source: ./nginx/ca-trust
      target: /etc/nginx/ca-trust
      read_only: true
    - type: bind
      bind:
        create_host_path: false
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
      read_only: true
    - type: bind
      bind:
        create_host_path: false
      source: ./nginx/nginx_ldap.conf
      target: /etc/nginx/nginx_ldap.conf
      read_only: true
    - type: bind
      bind:
        create_host_path: false
      source: ./nginx/htpasswd
      target: /etc/nginx/htpasswd
      read_only: true
    - type: bind
      bind:
        create_host_path: false
      source: ./nginx/certs
      target: /etc/nginx/certs
      read_only: true
    - type: bind
      bind:
        create_host_path: false
      source: ./nginx/certs/dhparam.pem
      target: /etc/nginx/dhparam/dhparam.pem
      read_only: true
    healthcheck:
      test: ["CMD", "curl", "--insecure", "--silent", "https://localhost:443"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    labels:
      traefik.enable : false
      # traefik.http.routers.openresty.rule: "Host(`test.example.org`)"
      # traefik.http.routers.openresty.entrypoints: "websecure"
      # traefik.http.routers.openresty.tls.certresolver: "myresolver"
      # traefik.http.services.openresty.loadbalancer.server.port: 443

networks:
  default:
    external: false
    # name: traefik-proxy

